# -*- coding: utf-8 -*-
"""NaanMudhalvanAI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BtV05VafueUExW0AifY4nAWrmqSJMdwb
"""

pip install pandas

pip install sentence-transformers

import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

data = {
    'source': ['This is the original document.', 'Another original document.', 'A completely original text.', 'hello hi there'],
    'plagiarized': ['This is a slightly modified version of the original document.', 'A slightly altered document.', 'A heavily plagiarized text.', 'hello there']
}
df = pd.DataFrame(data)

model = SentenceTransformer('average_word_embeddings_komninos')


plagiarism_results = []
for i in range(len(df)):
    source_encoding = model.encode([df['source'][i]])
    plagiarized_encoding = model.encode([df['plagiarized'][i]])
    similarity_score = cosine_similarity(source_encoding, plagiarized_encoding)[0][0]

    if similarity_score >= 0.7:
        plagiarism_results.append({
            'source': df['source'][i],
            'plagiarized': df['plagiarized'][i],
            'similarity_score': similarity_score
        })

if plagiarism_results:
    print("Plagiarized documents found:")
    for result in plagiarism_results:
        print(f"Source: {result['source']}")
        print(f"Plagiarized: {result['plagiarized']}")
        print(f"Similarity Score: {result['similarity_score']}")
        print()
else:
    print("No plagiarized documents found.")
